version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourSecurePassword123!"
    ports:
      - "1434:1433" # Porta mapeada (caso a 1433 já esteja em uso)
    volumes:
      - sql_data:/var/opt/mssql
      - ./init-sql:/docker-entrypoint-initdb.d # Incluindo o volume com scripts de inicialização
    networks:
      - app-network

  webapi:
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sql_data:
